name: Build & Publish Release APK

on:
 push:
  branches:
   - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Releasing using Hub
      uses: yurakurets/action-release-debugapk@master
      env:
       REPO_BRANCH: master
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APK_FOLDER: android/app/build/outputs/apk/release/app-release.apk
       APP_FOLDER: android/app
       RELEASE_TITLE: New Build
